path: C:\\Users\\Thor9\\OneDrive - Aalborg Universitet\\Dokumenter\\AAU\\Projektarbejde\\AAU-Racing-Driverless\\YOLO\\data
train: images\train
val: images\train


#classes
names:
  0: yellow_cone
  1: blue_cone
  2: orange_cone
  3: large_orange_cone
  4: unknown_cone